<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-0T3LLVM" failures="1" tests="3" name="TestNGFramework" time="10.374" errors="0" timestamp="2023-02-22T21:35:02 EST">
  <testcase classname="com.exelenter.testcases.LoginTest" name="validAdminLogin" time="1.829"/>
  <testcase classname="com.exelenter.testcases.LoginTest" name="validUserAnEmptyPassword" time="0.25">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at com.exelenter.testcases.LoginTest.validUserAnEmptyPassword(LoginTest.java:45)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- validUserAnEmptyPassword -->
  <testcase classname="com.exelenter.testcases.LoginTest" name="validUserInvalidPassword" time="0.0">
    <skipped/>
  </testcase> <!-- validUserInvalidPassword -->
</testsuite> <!-- TestNGFramework -->
